services:
  - docker
before_install:
  - docker build -t aamibot/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true aamibot/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-550829628760"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secrete_access_key:
    secure: "$AWS_SECRETE_KEY"

     
